### ISSUE TITLE
Major and Minor Bugs

### ISSUE THREAD

**Issue by kalapi** [alexeiva/GF2016-Glyph-Sets#1]
### Issues with the Encoding

Hi @alexeiva, I've found a few issues with the files. I've listed them below. These are by no means exhaustive, and i'll keep adding more as I find them. However, before we start fixing the following let's review them. @davelab6, can you have a quick look? 

Also, you (Alexei) can assign this to me that way you can get more time to find/fix Cyrillic stuff.

#### Major

- [x] Ỉ ỉ - These Vietnamese characters are included in Pro instead of Plus (line 88 & 89).
- [x]  '.case' variants of punctuation are missing. These should be included in Pro and Expert.
- [x]  '.dnom' and '.numr' variants of the numerals are missing in the Pro encoding.
- [x]  Error in line(s) 91, 92, and 93 in file 'google-latin-pro_unique-glyph.nam'. Character column has two commas instread of the unicode character.
- [x] Rename '00B7.sc' to 'periodcentered.sc' on line 256 in 'google-latin-expert_unique-glyphs.nam'.
- [x] Add Catalonian 'periodcentered.loclCAT' and 'periodcentered.loclCAT.case' to Plus.
- [x] Add Catalonian 'periodcentered.loclCAT.sc' to Expert

**Removed**: _Should we be using the following convention; 'Amacron.sc' instead of 'amacron.sc' since these glyphs are 'stylistic' variants of the Latin capital characters?_

#### Minor

- [x] If we're including uni25A0 (Geometric Black Square), we should also include uni25A1 (Geometric White Square).
- [x] Same as above but for 0x25C6 (Geometric Black Diamond). Also include 0x25C7 (Geometric White Diamond).
- [x] Maybe we should add 'T_h', 'c_t', and 's_t' in the expert set?
- [x] It may be worth including the 'extra' currency symbols in Plus itself. E.g. If I want to use the '₹' (Rupee symbol) when using Creepster.
- [x] Update name 'i.TRK' to 'i.loclTRK' in order to make it consistent with the Catalonian '.loclCAT' suffixes.

**Comment by davelab6** [comment]
> Ỉ ỉ - These Vietnamese characters are included in Pro instead of Plus (line 88 & 89).

Agree

>  '.case' variants of punctuation are missing. These should be included in Pro and Expert.

Agree

>  '.dnom' and '.numr' variants of the numerals are missing in the Pro encoding.

Agree

> Error in line(s) 91, 92, and 93 in file 'google-latin-pro_unique-glyph.nam'. Character column has two commas instread of the unicode character.

Agree

> Should we be using the following convention; 'Amacron.sc' instead of 'amacron.sc' since these glyphs are 'stylistic' variants of the Latin capital characters?

Not sure.

> If we're including uni25A0 (Geometric Black Square), we should also include uni25A1 (Geometric White Square).

Agree

> Same as above but for 0x25C6 (Geometric Black Diamond). Also include 0x25C7 (Geometric White Diamond).

Agree

> Maybe we should add 'T_h', 'c_t', and 's_t' in the expert set?

Agree

> It may be worth including the 'extra' currency symbols in Plus itself. E.g. If I want to use the '₹' (Rupee symbol) when using Creepster.

Agree

**Comment by alexeiva** [comment]
Good job, @kalapi. I am happy for you to take over from here. 
And please make sure Creepster issue is taken with great concern. 
Perhaps, you can also check the [Impallari Latin](https://github.com/impallari/Impallari-Fontlab-Encodings/blob/master/Impallari%20Latin/Impallari_Latin_v009.enc) to see if we can borrow more ligatures:
	f.calt	
	f_f	
	f_i 	
	f_l	
	f_f_i	
	f_f_l	
	f_b	
	f_f_b	
	f_h	
	f_f_h	
	f_j	
	f_f_j	
	f_k	
	f_f_k	
	f_t	
	f_f_t	
	c_h	
	c_k	
	c_p	
	c_t	
	e_t	
	l_l	
	s_p	
	s_t	
	t_h	
	t_t	
	t_z	
	IJ	
	ij

**Comment by kalapi** [comment]
In my opinion, the additional ligatures are only necessary on a case by case basis. They do not need to be hard-coded into the set, since not all of these will be necessary for all (Expert fonts). But it may be a good idea to maintain an additional document listing these and similar optional glyphs to be included?

**Comment by alexeiva** [comment]
@kalapi are you happy with renaming the uninames to glyphs nice names? 
uni1E63  > sdotbelow

**Comment by kalapi** [comment]
@alexeiva If GlyphsApp is happy with those names, I have no problem!

**Comment by alexeiva** [comment]
In Plus f_i, and f_l are duplicates included for legacy reasons. Are they still valid?
0xFB01  ﬁ fi
           **f_i**
0xFB02  ﬂ fl
           **f_l**

**Comment by alexeiva** [comment]
The total glyphs count in expert set is smaller now. 
@kalapi did you make any removals?

**Comment by kalapi** [comment]
@alexeiva,

1. I think it's ok to keep the ligature glyphs, in case that some of the existing fonts already use them. They are components anyway.

2. Negative on the latter. The earlier count was 267, now it is 273.

**Comment by kalapi** [comment]
@alexeiva Found one more bug in the Plus file (Image below).

![screen shot 2016-06-29 at 19 08 58](https://cloud.githubusercontent.com/assets/15804460/16456655/4156d5e0-3e36-11e6-8292-f50130b2d372.png)

Should ideally be:

![screen shot 2016-06-29 at 20 21 21](https://cloud.githubusercontent.com/assets/15804460/16456873/1d3b43a2-3e37-11e6-895b-fca48fa55b78.png)

Let me know if you want me to do these as well. It's important to note that for the '.null' and 'CR' it won't be possible to input the character in the second column as, in the case of '.null', it will be replaced with space, and in the case of 'CR' anything following it will be moved to the following line.

**Comment by davelab6** [comment]
Does glyphs autogenerate 'liga' code for 0xFB01 and 0xFB02 or is it only f_i
and f_l?

**Comment by davelab6** [comment]
On 29 June 2016 at 04:03, Kalapi Gajjar <notifications@github.com> wrote:

> it may be a good idea to maintain an additional document listing these and
> similar optional glyphs to be included?
>

I agree

**Comment by kalapi** [comment]
@davelab6 Glyphs does **not** auto-generate feature code for 'f_i' and 'f_l' which is a bit counter intuitive given that the '_' syntax recognition is a feature. It does however generate code for 'fi' and 'fl'. So we'll have to add the former manually or automate it using a script.

**Comment by davelab6** [comment]
Since f_i and f_l are unencoded, what's the point of them, other than to
discourage use of the legacy unicode fi and fl chars?

**Comment by kalapi** [comment]
I don't think there's any good reason other than to support fonts in the library that already include 'f_i' and 'f_l'. Which may == 0, in which case we should scrap it from the list.

**Comment by davelab6** [comment]
This is also a minimum; if other fonts already include all 4, then I
suggest encoding f_i and f_l as fl and fi

**Comment by alexeiva** [comment]
I will fix all this, and push to the main repo
