### ISSUE TITLE
Remove repo

### ISSUE THREAD

**Issue by davelab6** [alexeiva/GF2016-Glyph-Sets#2]
I suggest pushing the changes in this repo back to https://github.com/alexeiva/fonts/tree/master/tools/encodings/GF%202016%20Glyph%20Sets and then making a pull request so that Kalapi can post his comments on the pull request; and then remove this repo.

**Comment by alexeiva** [comment]
sorry, I don't get what you mean.
This repo is up-to-date with the recent nice-name-changes. 
I don't see any pull requests from Kalapi yet.

**Comment by alexeiva** [comment]
I have merged @kalapi's pull.
next up: I will change uni to nice names, and push to google/fonts repo

**Comment by davelab6** [comment]
Well, you cant make a PR from here to /google/fonts because you need to have a fork of /google/fonts to do that. 

So I suggested putting the latest version which is here into your 'fonts' fork. 

Then, since the purpose of this repo is to comment and collaborate on the files, if you make a PR from your fork to the google repo, then Kalapi can comment line by line on the files, and then you can update them - or kalapi can fork your fork and then make direct changes on his own branch, and then you can pull that branch into your branch. 

The branch in the pull request can be edited freely until it is merged :)

**Comment by alexeiva** [comment]
Alright, Dave I am deleting this repo
